# Generated by Django 3.1.4 on 2020-12-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailsvg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='svg',
            name='edit_code',
            field=models.TextField(blank=True, default=''),
        ),
    ]
