# Generated by Django 3.2.8 on 2021-10-12 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailsvg', '0002_svg_edit_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='svg',
            options={'ordering': ['-id']},
        ),
    ]
