# Generated by Django 3.1.4 on 2021-11-29 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailsvg', '0003_alter_svg_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='svg',
            name='edit_code',
        ),
    ]
