# Generated by Django 4.0.7 on 2022-09-15 18:16

from django.db import migrations, models
import wagtailsvg.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailsvg', '0004_remove_svg_edit_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svg',
            name='file',
            field=models.FileField(upload_to=wagtailsvg.models.get_svg_upload_to_folder, verbose_name='file'),
        ),
    ]
