# Generated by Django 4.2.5 on 2023-09-24 10:39

import django.core.files.storage
from django.db import migrations, models
import wagtailsvg.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailsvg', '0005_alter_svg_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svg',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to=wagtailsvg.models.get_svg_upload_to_folder, verbose_name='file'),
        ),
    ]
